### PR TITLE
Specify resulting encoding as optional parameter

### PR DESCRIPTION
**Pull request by plepe**
Add another option 'encoding' to specify the encoding of the resulting file.

### CODE REVIEW

**Comment by plepe** [comment]
Hmm, somethings not really working yet ...

**Comment by max-mapper** [comment]
Maybe a test case would help debug?

**Comment by plepe** [comment]
Apparently it's not so easy to represent strings in non-utf8 encoding in JS as I assumed ... Still trying.

**Comment by plepe** [comment]
I think it doesn't work. If I ever find a way, I will re-open the pull request :)

**Pull request closed without merging**
