### PR TITLE
Fix for writing large objects (more than 1024 keys)

### PR DESCRIPTION
**Pull request by mafintosh**

### CODE REVIEW

**Comment by karissa** [comment]
Nice! Would it be ok to try it with something like 100k columns?

**Comment by mafintosh** [comment]
I just tried 100k columns locally and it works but slows down the tests quite a bit so I'm not sure how feasible it would be to have that many cols

**Comment by karissa** [comment]
okay cool. just wanted to see if it worked.

**Comment by mafintosh** [comment]
Released in 1.0.0

**Pull request merged**
